### ISSUE TITLE
Controller crash when out of bounds

### ISSUE THREAD

**Issue by chiggy420** [git-moss/DrivenByMoss-Documentation#21]
This is the script console when the issue occurs.

Called init()
Firmware version: 259
Running.
Index -1 out of bounds for length 2
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 2
    at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
    at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
    at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
    at java.base/java.util.Objects.checkIndex(Unknown Source)
    at java.base/java.util.ArrayList.get(Unknown Source)
    at de.mossgrabers.framework.daw.data.bank.AbstractBank.getItem(AbstractBank.java:51)
    at de.mossgrabers.framework.view.AbstractSessionView.onGridNoteLongPress(AbstractSessionView.java:191)
    at de.mossgrabers.framework.controller.AbstractControlSurface.handleGridNote(AbstractControlSurface.java:984)
    at de.mossgrabers.framework.controller.AbstractControlSurface.lambda$createPads$3(AbstractControlSurface.java:191)
    at de.mossgrabers.framework.controller.hardware.AbstractHwButton.checkButtonState(AbstractHwButton.java:194)
    at com.bitwig.flt.control_surface.proxy.BitwigStudioHost$ScheduledTask.invokeCallback(SourceFile:715)
    at GOA.Mq(SourceFile:94)
    at GOA.MJU(SourceFile:90)
    at Vhc.Cnw(SourceFile:128)
    at gDB.fhB(SourceFile:76)
    at nHk.G1f(SourceFile:273)
    at FwH.Mq(SourceFile:329)
    at oM.Mq(SourceFile:205)
    at WIQ.run(SourceFile:91)
    at oM.run(SourceFile:106)

**Comment by git-moss** [comment]
Thanks, will be fixed in the next update.

**Comment by chiggy420** [comment]
Thanks for the reply, appreciate your help and the great script.
Truly a pleasure to use DrivenByMoss 🤘🏼
